# Generated by Django 3.1.1 on 2020-09-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200913_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamesSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_section', models.TextField(choices=[('CUL', 'Культура'), ('CIT', 'Город'), ('HEA', 'Здоровье'), ('SCI', 'Наука'), ('SPA', 'Космос'), ('IRE', 'Международные отношения')])),
                ('relation', models.ManyToManyField(to='articles.Article')),
            ],
        ),
    ]
