# Generated by Django 3.1.1 on 2020-09-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_namessections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namessections',
            name='relation',
            field=models.ManyToManyField(blank=True, related_name='sections', to='articles.Article'),
        ),
    ]
