# Generated by Django 3.1.1 on 2020-09-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200915_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namessections',
            name='name_of_section',
            field=models.TextField(choices=[('Культура', 'Культура'), ('Город', 'Город'), ('Здоровье', 'Здоровье'), ('Наука', 'Наука'), ('Космос', 'Космос'), ('Международные отношения', 'Международные отношения')]),
        ),
    ]
