# Generated by Django 3.1.1 on 2020-09-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200916_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namessections',
            name='relation',
        ),
    ]
