# Generated by Django 3.1.1 on 2020-09-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200916_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='Article',
            new_name='article',
        ),
    ]
