# Generated by Django 3.1.1 on 2020-09-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_namessections_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='namesections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.namessections'),
        ),
    ]
