# Generated by Django 3.1.1 on 2020-09-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200917_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namessections',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
