# Generated by Django 3.1.1 on 2020-09-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200918_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namessections',
            name='is_main',
        ),
        migrations.AddField(
            model_name='relationship',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
