# Generated by Django 3.1.1 on 2020-09-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200918_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sec',
            field=models.ManyToManyField(to='articles.NamesSections'),
        ),
    ]
