# Generated by Django 3.1.1 on 2020-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_sec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sec',
        ),
        migrations.RemoveField(
            model_name='namessections',
            name='relation',
        ),
        migrations.AddField(
            model_name='article',
            name='relation',
            field=models.ManyToManyField(related_name='sections', through='articles.Relationship', to='articles.NamesSections'),
        ),
    ]
