# Generated by Django 3.1.1 on 2020-09-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20200918_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='is_main',
            field=models.BooleanField(default=None),
        ),
    ]
